# Generated by Django 3.2.4 on 2021-06-13 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='copmleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
