# Generated by Django 3.2.4 on 2021-06-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='copmleted',
            new_name='completed',
        ),
    ]
