# Generated by Django 3.2.4 on 2021-06-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todo_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed_date',
        ),
    ]
