# Generated by Django 3.2.4 on 2021-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_remove_todo_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
